image: maven:latest

stages:
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/pha-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh sshpass
  script:
    - mv "target/pha-0.0.1-SNAPSHOT.jar" "target/app.jar"
    - sshpass -p "$REMOTE_PW" scp -o StrictHostKeyChecking=no target/app.jar root@"$REMOTE_HOST":/home/pha
    - sshpass -p "$REMOTE_PW" ssh root@"$REMOTE_HOST" "systemctl stop pha-api; systemctl start pha-api"
  only:
    - feature/cicd-spike 

