image: maven:latest

stages:
  - build
  - deploy
  # - test
  # - run

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  # script:
    # - mvn install -DskipTests
  script:
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/pha-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image: alpine:latest  # Use a lightweight image for deployment
  before_script:
    - apk add --no-cache openssh  # Install SSH client
  script:
    - mv "target/pha-0.0.1-SNAPSHOT.jar" "target/app.jar"
    - scp -o StrictHostKeyChecking=no target/app.jar root@139.180.155.250:/home/pha  # Replace with your server details
  only:
    - feature/cicd-spike 

    # test:
    #   stage: test
    #   script:
    # - mvn $MAVEN_CLI_OPTS test
    # - mvn test
    # - echo "Skip test~~"

# run:
#   stage: run
#   script:
#     - mvn package
#     - mvn exec:java -Dexec.mainClass="com.project.oss.OssApplication" -DskipTests

