image: maven:latest

stages:
  - cleanup
  - build
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

clean-env:
  stage: cleanup
  script:
    - echo "Started leaning up temporary files..."
    - rm -rf target/*


build:
  stage: build
  script:
    - mvn package -DskipTests=true
  artifacts:
    paths:
      - target/pha-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh sshpass
  script:
    # - echo "Copying app.jar to $REMOTE_HOST:/home/pha"
    # - mv "target/pha-0.0.1-SNAPSHOT.jar" "target/app.jar"
    # - sshpass -p "$REMOTE_PW" scp -o StrictHostKeyChecking=no target/app.jar "$REMOTE_USR"@"$REMOTE_HOST":/home/pha
    # - sshpass -p "$REMOTE_PW" ssh -o StrictHostKeyChecking=no "$REMOTE_USR"@"$REMOTE_HOST" "systemctl stop pha-api; systemctl start pha-api"
        # Add SSH key to ssh-agent
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # Disable strict host key checking
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
    # Test connection
    - ssh "$REMOTE_USR"@"$REMOTE_HOST" "echo Connected to remote server!"
  only:
    - feature/cicd-spike
