spring:
  application:
    name: PHA
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB


#   #DB Postgres SQL
  datasource:
    url: jdbc:postgresql://157.66.26.21:5432/pha
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  # datasource:
  #   url: jdbc:postgresql://localhost:5432/pha
  #   username: postgres
  #   password: 12345678
  #   driver-class-name: org.postgresql.Driver

  # JPA Setting
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  #mail
  mail:
      host: smtp.gmail.com
      port: 587
      username: lekhacminhhieu2311el@gmail.com
      password: twzv cpjf tekr xzpc
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

# Token
app:
  jwtSecret: ======================Pharmacy=Spring===========================
  jwtExpirationMs: 86400000

# S3 Bucket AWS
aws:
  bucket:
    name: bucket-sample
  region: ap-southeast-2
  accessKey: sample-key
  secretKey: sample-key

# Cloudinary
cloudinary:
  cloud_name: dmz6hapvj
  api_key: 359211291938856
  api_secret: D9fANGl5fK9Q1QGrwBv88fMtIY4

# Expiry Date
expiry:
  warning:
    days: 90

# Payment
payment:
  payOS:
    client_id: 26876906-65fd-4d08-afd2-c19fcada6857
    api_key: 4fe2a0c9-5986-4150-be96-263684e0014f
    checkSum_key: ee3386799b1e49366fb904e05b8cf21ce13b682e188b805513c0c305696293e3

logging:
  level:
    com.fu.pha.configuration.FirebaseConfig: INFO




