spring:
  application:
    name: PHA
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false

   #DB Postgres SQL
  datasource:
    url: jdbc:postgresql://139.180.155.250:5432/fu_pha
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

#  datasource:
#    url: jdbc:postgresql://localhost:5432/pha
#    username: postgres
#    password: 23112002
#    driver-class-name: org.postgresql.Driver

  # JPA Setting
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  #mail
  mail:
      host: smtp.gmail.com
      port: 587
      username: lekhacminhhieu2311el@gmail.com
      password: twzv cpjf tekr xzpc
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

# Token
app:
  jwtSecret: ======================Pharmacy=Spring===========================
  jwtExpirationMs: 86400000

# S3 Bucket AWS
aws:
  bucket:
    name: bucket-sample
  region: ap-southeast-2
  accessKey: sample-key
  secretKey: sample-key

# Cloudinary
cloudinary:
  cloud_name: dmz6hapvj
  api_key: 359211291938856
  api_secret: D9fANGl5fK9Q1QGrwBv88fMtIY4




